name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: gui
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: main

    - uses: actions/upload-artifact@v2
      with:
        name: gui
        path: gui/dist/windows
    - uses: actions/upload-artifact@v2
      with:
        name: main
        path: main/dist/windows
