name: Build and Deploy

on: push

env:
  PYINSTALLER_COMMAND: "pip install pyinstaller"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: ${{ env.PYINSTALLER_COMMAND }}

    - name: Build GUI exe
      run: |
            pyinstaller "gui/main.py" --onefile
            mv dist/main/main.exe dist/main/gui.exe

    - name: Build Main exe
      run: |
            pyinstaller "main/main.py" --onefile
            mv dist/main/main.exe dist/main/console.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: exe-files
        path: dist/main